// Comprehensive first-person training data from entrepreneur perspective (84 examples)
export const ENTREPRENEUR_TRAINING_DATA = [
  // GROWTH scenarios (14 examples) - First person perspective
  {
    id: "GROWTH_001",
    version: 1,
    text: "We finally crossed R300k MRR this month. I can feel the flywheel starting to turn.",
    expected_category: "Growth" as const,
    expected_mood: "Excited",
    expected_energy: "high" as const,
    confidence_range: [90, 95] as [number, number],
    business_context: "Recurring revenue milestone for a small SaaS",
    source: "entrepreneur_fp" as const
  },
  {
    id: "GROWTH_002",
    version: 1,
    text: "Our Cape Town pop-up doubled sales after I partnered with a local influencer.",
    expected_category: "Growth" as const,
    expected_mood: "Optimistic",
    expected_energy: "high" as const,
    confidence_range: [85, 95] as [number, number],
    business_context: "Retail activation driving demand",
    source: "entrepreneur_fp" as const
  },
  {
    id: "GROWTH_003",
    version: 1,
    text: "I shipped our first order to Namibia today — SADC expansion is officially real.",
    expected_category: "Growth" as const,
    expected_mood: "Confident",
    expected_energy: "high" as const,
    confidence_range: [85, 90] as [number, number],
    business_context: "First cross-border logistics success",
    source: "entrepreneur_fp" as const
  },
  {
    id: "GROWTH_004",
    version: 1,
    text: "The upsell email I wrote on Sunday nudged legacy clients to the Premium plan (+14% ARPU).",
    expected_category: "Growth" as const,
    expected_mood: "Pleased",
    expected_energy: "medium" as const,
    confidence_range: [85, 90] as [number, number],
    business_context: "Monetisation via upsells",
    source: "entrepreneur_fp" as const
  },
  {
    id: "GROWTH_005",
    version: 1,
    text: "Our API listing with a fintech aggregator started feeding qualified leads. Pipeline feels healthier.",
    expected_category: "Growth" as const,
    expected_mood: "Energised",
    expected_energy: "high" as const,
    confidence_range: [85, 90] as [number, number],
    business_context: "Channel partnership opening top of funnel",
    source: "entrepreneur_fp" as const
  },
  {
    id: "GROWTH_006",
    version: 1,
    text: "DocSafe content clusters I published are ranking — organic impressions are up 60%.",
    expected_category: "Growth" as const,
    expected_mood: "Encouraged",
    expected_energy: "medium" as const,
    confidence_range: [80, 90] as [number, number],
    business_context: "SEO strategy compounding traffic",
    source: "entrepreneur_fp" as const
  },
  {
    id: "GROWTH_007",
    version: 1,
    text: "Two accounting firms agreed to pilot our reseller programme. If it sticks, distribution gets easier.",
    expected_category: "Growth" as const,
    expected_mood: "Hopeful",
    expected_energy: "medium" as const,
    confidence_range: [80, 90] as [number, number],
    business_context: "B2B reseller motion",
    source: "entrepreneur_fp" as const
  },
  {
    id: "GROWTH_008",
    version: 1,
    text: "After a creative refresh, paid social finally hit a sustainable CAC:LTV. What a relief.",
    expected_category: "Growth" as const,
    expected_mood: "Relieved",
    expected_energy: "medium" as const,
    confidence_range: [80, 90] as [number, number],
    business_context: "Performance marketing efficiency",
    source: "entrepreneur_fp" as const
  },
  {
    id: "GROWTH_009",
    version: 1,
    text: "Our webinar sign-ups passed 500, mostly SMEs in Gauteng and KZN. The topic resonated.",
    expected_category: "Growth" as const,
    expected_mood: "Excited",
    expected_energy: "high" as const,
    confidence_range: [85, 95] as [number, number],
    business_context: "Education-led demand generation",
    source: "entrepreneur_fp" as const
  },
  {
    id: "GROWTH_010",
    version: 1,
    text: "Churn dipped from 5.1% to 3.4% after the onboarding tweaks I pushed last week.",
    expected_category: "Growth" as const,
    expected_mood: "Optimistic",
    expected_energy: "medium" as const,
    confidence_range: [85, 90] as [number, number],
    business_context: "Retention improvement from UX changes",
    source: "entrepreneur_fp" as const
  },
  {
    id: "GROWTH_011",
    version: 1,
    text: "I added a student tier and saw a spike in Friday payday sign-ups.",
    expected_category: "Growth" as const,
    expected_mood: "Curious",
    expected_energy: "medium" as const,
    confidence_range: [80, 88] as [number, number],
    business_context: "Pricing experiment unlocking new segment",
    source: "entrepreneur_fp" as const
  },
  {
    id: "GROWTH_012",
    version: 1,
    text: "The marketplace listing is steady: trials each week and a 19% conversion to paid.",
    expected_category: "Growth" as const,
    expected_mood: "Positive",
    expected_energy: "medium" as const,
    confidence_range: [80, 88] as [number, number],
    business_context: "Third-party marketplace channel",
    source: "entrepreneur_fp" as const
  },
  {
    id: "GROWTH_013",
    version: 1,
    text: "First partnership chat with a national distributor went well — could accelerate provincial reach.",
    expected_category: "Growth" as const,
    expected_mood: "Hopeful",
    expected_energy: "medium" as const,
    confidence_range: [80, 90] as [number, number],
    business_context: "Channel expansion discussion",
    source: "entrepreneur_fp" as const
  },
  {
    id: "GROWTH_014",
    version: 1,
    text: "Referrals are picking up since I introduced small rewards in the Goals module streaks.",
    expected_category: "Growth" as const,
    expected_mood: "Encouraged",
    expected_energy: "medium" as const,
    confidence_range: [80, 88] as [number, number],
    business_context: "Light gamification fueling growth",
    source: "entrepreneur_fp" as const
  },

  // CHALLENGE scenarios (14 examples)
  {
    id: "CHALLENGE_001",
    version: 1,
    text: "Load shedding during our live training session caused drop-offs. I need a backup plan for Stage 4 days.",
    expected_category: "Challenge" as const,
    expected_mood: "Frustrated",
    expected_energy: "medium" as const,
    confidence_range: [85, 95] as [number, number],
    business_context: "Power outage impacts live events",
    source: "entrepreneur_fp" as const
  },
  {
    id: "CHALLENGE_002",
    version: 1,
    text: "Cash flow is tight again. I'm skipping my own salary to make payroll.",
    expected_category: "Challenge" as const,
    expected_mood: "Stressed",
    expected_energy: "low" as const,
    confidence_range: [90, 95] as [number, number],
    business_context: "Liquidity crunch trade-off",
    source: "entrepreneur_fp" as const
  },
  {
    id: "CHALLENGE_003",
    version: 1,
    text: "My lead engineer resigned. I feel overwhelmed lining up replacements and keeping delivery on track.",
    expected_category: "Challenge" as const,
    expected_mood: "Overwhelmed",
    expected_energy: "low" as const,
    confidence_range: [85, 95] as [number, number],
    business_context: "Hiring gap increases risk",
    source: "entrepreneur_fp" as const
  },
  {
    id: "CHALLENGE_004",
    version: 1,
    text: "A client flagged a POPIA concern with DocSafe share links — I must tighten the copy and controls.",
    expected_category: "Challenge" as const,
    expected_mood: "Concerned",
    expected_energy: "medium" as const,
    confidence_range: [85, 90] as [number, number],
    business_context: "Compliance worry from customer",
    source: "entrepreneur_fp" as const
  },
  {
    id: "CHALLENGE_005",
    version: 1,
    text: "Hardware supplier pushed delivery by two weeks, which puts our KZN rollout at risk.",
    expected_category: "Challenge" as const,
    expected_mood: "Anxious",
    expected_energy: "medium" as const,
    confidence_range: [85, 90] as [number, number],
    business_context: "Supply chain delay",
    source: "entrepreneur_fp" as const
  },
  {
    id: "CHALLENGE_006",
    version: 1,
    text: "We had a 47-minute API outage due to bad cache invalidation. Painful but fixable.",
    expected_category: "Challenge" as const,
    expected_mood: "Determined",
    expected_energy: "medium" as const,
    confidence_range: [85, 95] as [number, number],
    business_context: "Production incident",
    source: "entrepreneur_fp" as const
  },
  {
    id: "CHALLENGE_007",
    version: 1,
    text: "Two chargebacks hit today. Not sure if it's fraud or confusion — I'm sifting through logs.",
    expected_category: "Challenge" as const,
    expected_mood: "Worried",
    expected_energy: "low" as const,
    confidence_range: [80, 90] as [number, number],
    business_context: "Payments risk",
    source: "entrepreneur_fp" as const
  },
  {
    id: "CHALLENGE_008",
    version: 1,
    text: "A competitor launched a limited-time price cut and my pipeline slowed overnight.",
    expected_category: "Challenge" as const,
    expected_mood: "Uneasy",
    expected_energy: "medium" as const,
    confidence_range: [80, 90] as [number, number],
    business_context: "Competitive pressure",
    source: "entrepreneur_fp" as const
  },
  {
    id: "CHALLENGE_009",
    version: 1,
    text: "Our NPS dropped after we changed support hours. Not happy — I need to rethink coverage.",
    expected_category: "Challenge" as const,
    expected_mood: "Disappointed",
    expected_energy: "low" as const,
    confidence_range: [80, 90] as [number, number],
    business_context: "Customer satisfaction slump",
    source: "entrepreneur_fp" as const
  },
  {
    id: "CHALLENGE_010",
    version: 1,
    text: "Board prep was tense — we missed Q2 targets and I felt the heat.",
    expected_category: "Challenge" as const,
    expected_mood: "Pressured",
    expected_energy: "low" as const,
    confidence_range: [80, 90] as [number, number],
    business_context: "Governance pressure",
    source: "entrepreneur_fp" as const
  },
  {
    id: "CHALLENGE_011",
    version: 1,
    text: "Duplicate records slipped into the CRM, so my reports are unreliable until I clean them.",
    expected_category: "Challenge" as const,
    expected_mood: "Irritated",
    expected_energy: "medium" as const,
    confidence_range: [80, 90] as [number, number],
    business_context: "Data hygiene issue",
    source: "entrepreneur_fp" as const
  },
  {
    id: "CHALLENGE_012",
    version: 1,
    text: "Customs held our demo units at OR Tambo. The training schedule is wobbling.",
    expected_category: "Challenge" as const,
    expected_mood: "Frustrated",
    expected_energy: "medium" as const,
    confidence_range: [80, 90] as [number, number],
    business_context: "Logistics delay",
    source: "entrepreneur_fp" as const
  },
  {
    id: "CHALLENGE_013",
    version: 1,
    text: "My inbox is chaos. I'm missing leads and it hurts to admit it.",
    expected_category: "Challenge" as const,
    expected_mood: "Overwhelmed",
    expected_energy: "low" as const,
    confidence_range: [80, 88] as [number, number],
    business_context: "Operational strain / productivity",
    source: "entrepreneur_fp" as const
  },
  {
    id: "CHALLENGE_014",
    version: 1,
    text: "Client feedback stung today — they said our onboarding felt 'unclear'. Not what I wanted to hear.",
    expected_category: "Challenge" as const,
    expected_mood: "Deflated",
    expected_energy: "low" as const,
    confidence_range: [80, 88] as [number, number],
    business_context: "CX gap creating friction",
    source: "entrepreneur_fp" as const
  },

  // ACHIEVEMENT scenarios (14 examples)
  {
    id: "ACHIEVEMENT_001",
    version: 1,
    text: "We hit break-even this month. Quietly proud of how far we've come.",
    expected_category: "Achievement" as const,
    expected_mood: "Proud",
    expected_energy: "medium" as const,
    confidence_range: [90, 95] as [number, number],
    business_context: "Financial sustainability milestone",
    source: "entrepreneur_fp" as const
  },
  {
    id: "ACHIEVEMENT_002",
    version: 1,
    text: "The new onboarding flow pushed activation up 18% this week — huge win.",
    expected_category: "Achievement" as const,
    expected_mood: "Accomplished",
    expected_energy: "high" as const,
    confidence_range: [85, 95] as [number, number],
    business_context: "Product impact",
    source: "entrepreneur_fp" as const
  },
  {
    id: "ACHIEVEMENT_003",
    version: 1,
    text: "We signed our first university client after a tough security review.",
    expected_category: "Achievement" as const,
    expected_mood: "Validated",
    expected_energy: "high" as const,
    confidence_range: [85, 95] as [number, number],
    business_context: "Enterprise credibility",
    source: "entrepreneur_fp" as const
  },
  {
    id: "ACHIEVEMENT_004",
    version: 1,
    text: "Our Women's Day campaign doubled engagement targets — the message landed perfectly.",
    expected_category: "Achievement" as const,
    expected_mood: "Delighted",
    expected_energy: "high" as const,
    confidence_range: [85, 90] as [number, number],
    business_context: "Marketing success",
    source: "entrepreneur_fp" as const
  },
  {
    id: "ACHIEVEMENT_005",
    version: 1,
    text: "Closed a multi-year deal with a national distributor. Future me will thank current me.",
    expected_category: "Achievement" as const,
    expected_mood: "Triumphant",
    expected_energy: "high" as const,
    confidence_range: [90, 95] as [number, number],
    business_context: "Strategic partnership",
    source: "entrepreneur_fp" as const
  },
  {
    id: "ACHIEVEMENT_006",
    version: 1,
    text: "We were named a top startup in the Western Cape tech awards. Team is buzzing.",
    expected_category: "Achievement" as const,
    expected_mood: "Grateful",
    expected_energy: "high" as const,
    confidence_range: [85, 90] as [number, number],
    business_context: "External recognition",
    source: "entrepreneur_fp" as const
  },
  {
    id: "ACHIEVEMENT_007",
    version: 1,
    text: "Accessibility updates shipped and a user wrote to say they finally feel included.",
    expected_category: "Achievement" as const,
    expected_mood: "Moved",
    expected_energy: "medium" as const,
    confidence_range: [85, 90] as [number, number],
    business_context: "Inclusive design impact",
    source: "entrepreneur_fp" as const
  },
  {
    id: "ACHIEVEMENT_008",
    version: 1,
    text: "Our customer success playbook cut escalations by 40%. It's calmer in support.",
    expected_category: "Achievement" as const,
    expected_mood: "Satisfied",
    expected_energy: "medium" as const,
    confidence_range: [85, 90] as [number, number],
    business_context: "Operational excellence",
    source: "entrepreneur_fp" as const
  },
  {
    id: "ACHIEVEMENT_009",
    version: 1,
    text: "First full team day in our Cape Town space. Morale is sky-high.",
    expected_category: "Achievement" as const,
    expected_mood: "Happy",
    expected_energy: "high" as const,
    confidence_range: [80, 90] as [number, number],
    business_context: "Culture boost",
    source: "entrepreneur_fp" as const
  },
  {
    id: "ACHIEVEMENT_010",
    version: 1,
    text: "We passed our first security audit with zero critical findings.",
    expected_category: "Achievement" as const,
    expected_mood: "Relieved",
    expected_energy: "high" as const,
    confidence_range: [85, 95] as [number, number],
    business_context: "Compliance win",
    source: "entrepreneur_fp" as const
  },
  {
    id: "ACHIEVEMENT_011",
    version: 1,
    text: "The BizBuilder budget calculator passed QA and went live without issues.",
    expected_category: "Achievement" as const,
    expected_mood: "Pleased",
    expected_energy: "medium" as const,
    confidence_range: [80, 90] as [number, number],
    business_context: "Feature delivery",
    source: "entrepreneur_fp" as const
  },
  {
    id: "ACHIEVEMENT_012",
    version: 1,
    text: "Average first response time is now under two minutes. Proud of the CS team.",
    expected_category: "Achievement" as const,
    expected_mood: "Proud",
    expected_energy: "high" as const,
    confidence_range: [85, 90] as [number, number],
    business_context: "Service excellence",
    source: "entrepreneur_fp" as const
  },
  {
    id: "ACHIEVEMENT_013",
    version: 1,
    text: "Our LinkedIn thought-leadership series hit 50k impressions this month.",
    expected_category: "Achievement" as const,
    expected_mood: "Encouraged",
    expected_energy: "medium" as const,
    confidence_range: [80, 88] as [number, number],
    business_context: "Brand awareness growth",
    source: "entrepreneur_fp" as const
  },
  {
    id: "ACHIEVEMENT_014",
    version: 1,
    text: "I negotiated better rates with our payment provider — margins just got healthier.",
    expected_category: "Achievement" as const,
    expected_mood: "Content",
    expected_energy: "medium" as const,
    confidence_range: [80, 88] as [number, number],
    business_context: "Unit economics improvement",
    source: "entrepreneur_fp" as const
  },

  // PLANNING scenarios (14 examples)
  {
    id: "PLANNING_001",
    version: 1,
    text: "I'm sketching the Q4 marketing plan: webinars, SEO clusters, and two partner co-marketing plays.",
    expected_category: "Planning" as const,
    expected_mood: "Organised",
    expected_energy: "medium" as const,
    confidence_range: [85, 90] as [number, number],
    business_context: "Quarterly campaign planning",
    source: "entrepreneur_fp" as const
  },
  {
    id: "PLANNING_002",
    version: 1,
    text: "I mapped a hiring plan: one full-stack dev, one data analyst, and a CS manager.",
    expected_category: "Planning" as const,
    expected_mood: "Focused",
    expected_energy: "medium" as const,
    confidence_range: [80, 90] as [number, number],
    business_context: "Workforce planning",
    source: "entrepreneur_fp" as const
  },
  {
    id: "PLANNING_003",
    version: 1,
    text: "I'm drafting a POPIA compliance roadmap with policy updates and staff training.",
    expected_category: "Planning" as const,
    expected_mood: "Methodical",
    expected_energy: "medium" as const,
    confidence_range: [85, 90] as [number, number],
    business_context: "Regulatory alignment",
    source: "entrepreneur_fp" as const
  },
  {
    id: "PLANNING_004",
    version: 1,
    text: "Scheduling a phased DocSafe migration to Cloudflare R2 to cut storage costs.",
    expected_category: "Planning" as const,
    expected_mood: "Analytical",
    expected_energy: "medium" as const,
    confidence_range: [80, 90] as [number, number],
    business_context: "Infrastructure move",
    source: "entrepreneur_fp" as const
  },
  {
    id: "PLANNING_005",
    version: 1,
    text: "I'm preparing the investor update with revised KPIs and runway outlook.",
    expected_category: "Planning" as const,
    expected_mood: "Measured",
    expected_energy: "medium" as const,
    confidence_range: [80, 90] as [number, number],
    business_context: "Stakeholder communication",
    source: "entrepreneur_fp" as const
  },
  {
    id: "PLANNING_006",
    version: 1,
    text: "Setting OKRs to lift activation by 10% and cut churn by 1.5pp.",
    expected_category: "Planning" as const,
    expected_mood: "Determined",
    expected_energy: "medium" as const,
    confidence_range: [80, 90] as [number, number],
    business_context: "Outcome-driven goal setting",
    source: "entrepreneur_fp" as const
  },
  {
    id: "PLANNING_007",
    version: 1,
    text: "Designing a coaching programme that turns our Training library into weekly action.",
    expected_category: "Planning" as const,
    expected_mood: "Constructive",
    expected_energy: "medium" as const,
    confidence_range: [80, 90] as [number, number],
    business_context: "Customer enablement",
    source: "entrepreneur_fp" as const
  },
  {
    id: "PLANNING_008",
    version: 1,
    text: "Scoping a pilot for Afrikaans UI across key views — localisation matters here.",
    expected_category: "Planning" as const,
    expected_mood: "Optimistic",
    expected_energy: "medium" as const,
    confidence_range: [80, 88] as [number, number],
    business_context: "i18n planning for SA",
    source: "entrepreneur_fp" as const
  },
  {
    id: "PLANNING_009",
    version: 1,
    text: "Building a price-test matrix for monthly vs annual plans with an upfront discount.",
    expected_category: "Planning" as const,
    expected_mood: "Analytical",
    expected_energy: "medium" as const,
    confidence_range: [80, 90] as [number, number],
    business_context: "Pricing experiments",
    source: "entrepreneur_fp" as const
  },
  {
    id: "PLANNING_010",
    version: 1,
    text: "Drafting a crisis comms plan for outages and security incidents. I don't want to wing it anymore.",
    expected_category: "Planning" as const,
    expected_mood: "Prepared",
    expected_energy: "medium" as const,
    confidence_range: [80, 90] as [number, number],
    business_context: "Risk mitigation",
    source: "entrepreneur_fp" as const
  },
  {
    id: "PLANNING_011",
    version: 1,
    text: "Creating a content calendar for LinkedIn to spotlight real SME wins.",
    expected_category: "Planning" as const,
    expected_mood: "Organised",
    expected_energy: "medium" as const,
    confidence_range: [80, 88] as [number, number],
    business_context: "Editorial planning",
    source: "entrepreneur_fp" as const
  },
  {
    id: "PLANNING_012",
    version: 1,
    text: "Writing requirements for an in-app referral programme that rewards actual conversions.",
    expected_category: "Planning" as const,
    expected_mood: "Practical",
    expected_energy: "medium" as const,
    confidence_range: [80, 88] as [number, number],
    business_context: "Growth loop design",
    source: "entrepreneur_fp" as const
  },
  {
    id: "PLANNING_013",
    version: 1,
    text: "I'm mapping a sales play for the hospitality sector ahead of December seasonality.",
    expected_category: "Planning" as const,
    expected_mood: "Strategic",
    expected_energy: "medium" as const,
    confidence_range: [80, 90] as [number, number],
    business_context: "Segment playbook",
    source: "entrepreneur_fp" as const
  },
  {
    id: "PLANNING_014",
    version: 1,
    text: "Blocking Fridays for deep work on product strategy — no meetings.",
    expected_category: "Planning" as const,
    expected_mood: "Resolved",
    expected_energy: "medium" as const,
    confidence_range: [80, 88] as [number, number],
    business_context: "Founder productivity system",
    source: "entrepreneur_fp" as const
  },
  {
    id: "PLANNING_015",
    version: 1,
    text: "Spent the entire day working on our 2025 strategic plan. I've been analyzing market trends, competitor movements, and our internal capabilities to chart our course for next year. The key priorities are: expanding our AI capabilities, entering two new market verticals, and building a world-class customer success organization. I've outlined quarterly milestones, budget allocations, and hiring plans. The most challenging part is balancing aggressive growth targets with sustainable operations. I want to grow fast but not at the expense of product quality or team burnout. I've scheduled presentations with the board next week to get their input before finalizing our direction.",
    expected_category: "Planning" as const,
    expected_mood: "Strategic",
    expected_energy: "medium" as const,
    confidence_range: [90, 95] as [number, number],
    business_context: "Annual strategic planning and business direction",
    source: "entrepreneur_fp" as const
  },

  // LEARNING scenarios (14 examples)
  {
    id: "LEARNING_001",
    version: 1,
    text: "Customer interviews taught me our 14-day trial is too short for SMEs to see value.",
    expected_category: "Learning" as const,
    expected_mood: "Reflective",
    expected_energy: "medium" as const,
    confidence_range: [85, 90] as [number, number],
    business_context: "Voice of customer insight",
    source: "entrepreneur_fp" as const
  },
  {
    id: "LEARNING_002",
    version: 1,
    text: "I learned that WhatsApp beats email for urgent support in SA — we'll staff for it.",
    expected_category: "Learning" as const,
    expected_mood: "Insightful",
    expected_energy: "medium" as const,
    confidence_range: [80, 90] as [number, number],
    business_context: "Channel preference learning",
    source: "entrepreneur_fp" as const
  },
  {
    id: "LEARNING_003",
    version: 1,
    text: "Post-mortem: alert noise was insane; I need thresholds and proper runbooks.",
    expected_category: "Learning" as const,
    expected_mood: "Analytical",
    expected_energy: "medium" as const,
    confidence_range: [80, 90] as [number, number],
    business_context: "Operations learning",
    source: "entrepreneur_fp" as const
  },
  {
    id: "LEARNING_004",
    version: 1,
    text: "Our Afrikaans copy needs a professional review — a few terms read awkwardly.",
    expected_category: "Learning" as const,
    expected_mood: "Thoughtful",
    expected_energy: "medium" as const,
    confidence_range: [80, 88] as [number, number],
    business_context: "Localisation quality",
    source: "entrepreneur_fp" as const
  },
  {
    id: "LEARNING_005",
    version: 1,
    text: "Beta testers struggled with DocSafe permissions; my labels weren't clear enough.",
    expected_category: "Learning" as const,
    expected_mood: "Concerned",
    expected_energy: "medium" as const,
    confidence_range: [80, 90] as [number, number],
    business_context: "Usability lesson",
    source: "entrepreneur_fp" as const
  },
  {
    id: "LEARNING_006",
    version: 1,
    text: "Shorter headlines lifted CTR; long copy tanked conversions — keep it tight.",
    expected_category: "Learning" as const,
    expected_mood: "Curious",
    expected_energy: "medium" as const,
    confidence_range: [80, 90] as [number, number],
    business_context: "Experimentation takeaway",
    source: "entrepreneur_fp" as const
  },
  {
    id: "LEARNING_007",
    version: 1,
    text: "Accountants want CSV and Xero export — I underestimated that workflow.",
    expected_category: "Learning" as const,
    expected_mood: "Humbled",
    expected_energy: "low" as const,
    confidence_range: [80, 90] as [number, number],
    business_context: "Feature gap recognition",
    source: "entrepreneur_fp" as const
  },
  {
    id: "LEARNING_008",
    version: 1,
    text: "Cohort analysis suggests Friday onboarding emails arrive too late to act on.",
    expected_category: "Learning" as const,
    expected_mood: "Analytical",
    expected_energy: "medium" as const,
    confidence_range: [80, 88] as [number, number],
    business_context: "Lifecycle timing insight",
    source: "entrepreneur_fp" as const
  },
  {
    id: "LEARNING_009",
    version: 1,
    text: "Using rands in examples increases trust — dollars feel foreign to our audience.",
    expected_category: "Learning" as const,
    expected_mood: "Practical",
    expected_energy: "medium" as const,
    confidence_range: [80, 90] as [number, number],
    business_context: "Localisation insight for SA",
    source: "entrepreneur_fp" as const
  },
  {
    id: "LEARNING_010",
    version: 1,
    text: "Our training videos load slowly on mobile data — I'll compress and add captions.",
    expected_category: "Learning" as const,
    expected_mood: "Resolved",
    expected_energy: "medium" as const,
    confidence_range: [80, 88] as [number, number],
    business_context: "Media optimisation",
    source: "entrepreneur_fp" as const
  },
  {
    id: "LEARNING_011",
    version: 1,
    text: "Removing the free tier boosted trial-to-paid but sign-ups dipped — trade-off noted.",
    expected_category: "Learning" as const,
    expected_mood: "Balanced",
    expected_energy: "medium" as const,
    confidence_range: [80, 90] as [number, number],
    business_context: "Pricing funnel dynamics",
    source: "entrepreneur_fp" as const
  },
  {
    id: "LEARNING_012",
    version: 1,
    text: "Sales calls reminded me to avoid jargon; plain language wins deals.",
    expected_category: "Learning" as const,
    expected_mood: "Encouraged",
    expected_energy: "medium" as const,
    confidence_range: [80, 88] as [number, number],
    business_context: "Messaging clarity",
    source: "entrepreneur_fp" as const
  },
  {
    id: "LEARNING_013",
    version: 1,
    text: "I noticed founders like me journal more when there's a daily nudge — streaks help.",
    expected_category: "Learning" as const,
    expected_mood: "Observant",
    expected_energy: "medium" as const,
    confidence_range: [80, 88] as [number, number],
    business_context: "Engagement behaviour insight",
    source: "entrepreneur_fp" as const
  },
  {
    id: "LEARNING_014",
    version: 1,
    text: "Meeting notes are scattered. I need a single source of truth in the Journal.",
    expected_category: "Learning" as const,
    expected_mood: "Determined",
    expected_energy: "medium" as const,
    confidence_range: [80, 88] as [number, number],
    business_context: "Process improvement need",
    source: "entrepreneur_fp" as const
  },

  // RESEARCH scenarios (14 examples)
  {
    id: "RESEARCH_001",
    version: 1,
    text: "I'm comparing R2 vs S3 costs for a POPIA-friendly storage setup.",
    expected_category: "Research" as const,
    expected_mood: "Analytical",
    expected_energy: "medium" as const,
    confidence_range: [85, 90] as [number, number],
    business_context: "Infra cost + compliance study",
    source: "entrepreneur_fp" as const
  },
  {
    id: "RESEARCH_002",
    version: 1,
    text: "I sent a survey to SMEs about which invoicing tools we should integrate with.",
    expected_category: "Research" as const,
    expected_mood: "Curious",
    expected_energy: "medium" as const,
    confidence_range: [80, 90] as [number, number],
    business_context: "Ecosystem research",
    source: "entrepreneur_fp" as const
  },
  {
    id: "RESEARCH_003",
    version: 1,
    text: "I read up on SARS tax bracket changes so the estimator stays accurate.",
    expected_category: "Research" as const,
    expected_mood: "Methodical",
    expected_energy: "medium" as const,
    confidence_range: [85, 90] as [number, number],
    business_context: "Regulatory update research",
    source: "entrepreneur_fp" as const
  },
  {
    id: "RESEARCH_004",
    version: 1,
    text: "I'm benchmarking competitor onboarding to shorten time-to-value.",
    expected_category: "Research" as const,
    expected_mood: "Focused",
    expected_energy: "medium" as const,
    confidence_range: [80, 90] as [number, number],
    business_context: "Competitive analysis",
    source: "entrepreneur_fp" as const
  },
  {
    id: "RESEARCH_005",
    version: 1,
    text: "I'm analysing dispute rates across payment providers to pick the safest option.",
    expected_category: "Research" as const,
    expected_mood: "Investigative",
    expected_energy: "medium" as const,
    confidence_range: [80, 90] as [number, number],
    business_context: "Vendor selection",
    source: "entrepreneur_fp" as const
  },
  {
    id: "RESEARCH_006",
    version: 1,
    text: "I'm running a conjoint survey to test pricing tiers and feature bundles.",
    expected_category: "Research" as const,
    expected_mood: "Analytical",
    expected_energy: "medium" as const,
    confidence_range: [80, 90] as [number, number],
    business_context: "Quant research for pricing",
    source: "entrepreneur_fp" as const
  },
  {
    id: "RESEARCH_007",
    version: 1,
    text: "I'm exploring voice-to-text APIs for journal entries with mood detection.",
    expected_category: "Research" as const,
    expected_mood: "Exploratory",
    expected_energy: "medium" as const,
    confidence_range: [80, 88] as [number, number],
    business_context: "Feasibility research",
    source: "entrepreneur_fp" as const
  },
  {
    id: "RESEARCH_008",
    version: 1,
    text: "I'm collecting qualitative feedback on the Goals page from 15 users this week.",
    expected_category: "Research" as const,
    expected_mood: "Inquisitive",
    expected_energy: "medium" as const,
    confidence_range: [80, 90] as [number, number],
    business_context: "Usability interviews",
    source: "entrepreneur_fp" as const
  },
  {
    id: "RESEARCH_009",
    version: 1,
    text: "Heatmaps show weak engagement with DocSafe sidebar icons — time to rethink IA.",
    expected_category: "Research" as const,
    expected_mood: "Curious",
    expected_energy: "medium" as const,
    confidence_range: [80, 88] as [number, number],
    business_context: "Behavioural analytics",
    source: "entrepreneur_fp" as const
  },
  {
    id: "RESEARCH_010",
    version: 1,
    text: "I'm evaluating BI connectors to push metrics into Looker Studio for weekly reports.",
    expected_category: "Research" as const,
    expected_mood: "Analytical",
    expected_energy: "medium" as const,
    confidence_range: [80, 90] as [number, number],
    business_context: "Reporting integration",
    source: "entrepreneur_fp" as const
  },
  {
    id: "RESEARCH_011",
    version: 1,
    text: "I'm sizing demand for coach/mentor workspaces among SA SMEs.",
    expected_category: "Research" as const,
    expected_mood: "Open-minded",
    expected_energy: "medium" as const,
    confidence_range: [80, 88] as [number, number],
    business_context: "Opportunity sizing",
    source: "entrepreneur_fp" as const
  },
  {
    id: "RESEARCH_012",
    version: 1,
    text: "I'm investigating offline-first sync for low-bandwidth regions.",
    expected_category: "Research" as const,
    expected_mood: "Pragmatic",
    expected_energy: "medium" as const,
    confidence_range: [80, 90] as [number, number],
    business_context: "Technical feasibility",
    source: "entrepreneur_fp" as const
  },
  {
    id: "RESEARCH_013",
    version: 1,
    text: "I'm testing whether adding a 'Quick Add Journal' on Home lifts daily entries.",
    expected_category: "Research" as const,
    expected_mood: "Curious",
    expected_energy: "medium" as const,
    confidence_range: [80, 88] as [number, number],
    business_context: "Product experiment tied to Home module",
    source: "entrepreneur_fp" as const
  },
  {
    id: "RESEARCH_014",
    version: 1,
    text: "I'm reviewing customer journeys to spot where Goals and Training should cross-link.",
    expected_category: "Research" as const,
    expected_mood: "Analytical",
    expected_energy: "medium" as const,
    confidence_range: [80, 90] as [number, number],
    business_context: "Journey mapping",
    source: "entrepreneur_fp" as const
  }
];